---
roles:
  - name: githubixx.docker
    src: https://github.com/githubixx/ansible-role-docker
    version: master
    scm: git
  - name: geerlingguy.ansible-role-nfs
    src: https://github.com/geerlingguy/ansible-role-nfs
    version: master
    scm: git
